Implement RFC 6742 RR Types
PowerDNS/pdns pull request #10121
Opened 2021-02-25 09:55 UTC by pieterlexis

### Short description
This commit implements the NID, L32, L64, and LP record types from RFC
6742. `dig` can properly parse the wiredata we send, and with the added
tests, I'm certain of the implementation.

The RFC has optional additional processing, this is not implemented.

Closes #10119

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

2021-02-25 13:52 UTC, Habbie requested changes
This has endianness problems that don't show because it has exactly the right amount of them ;)

2021-03-01 13:28 UTC, pieterlexis commented
> This has endianness problems that don't show because it has exactly the right amount of them ;)

I _think_ those are fixed now

2021-03-01 13:31 UTC, pieterlexis commented on pdns/misc.hh
> +inline uint64_t pdns_htonll(const uint64_t in) {
Should become `pdns::htonll`

2021-03-02 09:33 UTC, pieterlexis commented
```
test-dnswriter_cc.cc:305:19: error: array initializer must be an initializer list or string literal
  NodeOrLocatorID in({0, 0, 0, 0, 0, 0, 0, 1});
                  ^
1 error generated.
```

this is me :)

2021-03-03 09:38 UTC, Habbie requested changes

2021-03-03 09:38 UTC, Habbie commented on pdns/dnswriter.cc
> +  d_content.insert(d_content.end(), val, val + sizeof(&val));
shouldn't that be `sizeof(val)`?

2021-03-03 09:38 UTC, Habbie commented on pdns/rcpgenerator.cc
> +  }
This should probably count colons, not total bytes.

2021-03-03 09:38 UTC, Habbie commented on pdns/rcpgenerator.cc
> +  string to_parse = d_string.substr(d_pos, len) + "::";
Or, append `:0:0:0:0` here instead of `::` so a wrong colon count above is caught by `inet_pton` below.

2021-03-03 09:38 UTC, Habbie commented on pdns/test-dnswriter_cc.cc
> +  DNSPacketWriter pwR(packet, name, QType::NID, QClass::IN, 0);
`pwR` is a confusing name for a packet writer :-)

2021-03-31 12:08 UTC, Habbie commented
Can you add the types to the already existing note in upgrading.rst (currently says `CSYNC` and `IPSECKEY`), and fix the conflict? Then we can merge this.

2021-04-01 09:32 UTC, Habbie approved these changes

2021-04-01 09:32 UTC, merged

2021-04-01 12:48 UTC, saleem-bhatti commented
Thank you all -- I am very grateful for all your efforts!

Cheers,
--/Saleem