Spelling
PowerDNS/pdns pull request #10168
Opened 2021-03-11 10:18 UTC by jsoref

### Short description

### Checklist

I have:
- [ ] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2021-03-11 10:21 UTC, pieterlexis commented on modules/remotebackend/pipeconnector.cc
> +  // written routine - socket may not accept al data in one go
`writen` is valid.. it is a `write()` that writes `n` bytes

2021-03-11 10:25 UTC, rgacogne requested changes
I don't know what happened but some symbolic links have been turned into a copy of the target, duplicating code.

2021-03-11 10:27 UTC, jsoref commented
Sigh, one of my tools is stupid. I'll find the commits that need to be undone.

2021-03-12 09:19 UTC, rgacogne approved these changes
LGTM, nice work!

2021-03-12 13:07 UTC, Habbie requested changes
Thanks for this! I posted 5 commit suggestions. 3 of them are reversing a mistaken change from 'additionals' to 'additional'. The other 2 are errors I noticed that you did not cause but are so close to your work that we might as well do them now - also if I PRd those now they would conflict with your work.

If you take all 5 commits, I'll approve this.

2021-03-12 13:07 UTC, Habbie commented on pdns/iputils.hh
>      if it is matched by zero or more of the Netmask classes within.
```suggestion
    if it is matched by one or more of the Netmask classes within.
```

2021-03-12 13:07 UTC, Habbie commented on pdns/lua-record.cc
> +   unify ifupurl/ifportup
```suggestion
   unify ifurlup/ifportup
```

2021-03-12 13:07 UTC, Habbie commented on pdns/test-dnsdist_cc.cc
> +static void validateQuery(const PacketBuffer& packet, bool hasEdns=true, bool hasXPF=false, uint16_t additional=0, uint16_t answers=0, uint16_t authorities=0)
```suggestion
static void validateQuery(const PacketBuffer& packet, bool hasEdns=true, bool hasXPF=false, uint16_t additionals=0, uint16_t answers=0, uint16_t authorities=0)
```

2021-03-12 13:07 UTC, Habbie commented on pdns/test-dnsdist_cc.cc
> +  uint16_t expectedARCount = additional + (hasEdns ? 1U : 0U) + (hasXPF ? 1U : 0U);
```suggestion
  uint16_t expectedARCount = additionals + (hasEdns ? 1U : 0U) + (hasXPF ? 1U : 0U);
```

2021-03-12 13:07 UTC, Habbie commented on regression-tests/tests/too-big-for-udp-query-always-truncate-additional/description
> +the information that causes things to go over limit are 'courtesy' additional.
```suggestion
the information that causes things to go over limit are 'courtesy' additionals.
```

2021-03-12 18:58 UTC, merged