rec: make sure we take the right minimum for the PC TTL data.
PowerDNS/pdns pull request #10185
Opened 2021-03-17 15:02 UTC by omoerbeek

Also add safety belt to the ageing code to not wrap TTLs.

### Short description

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-03-17 15:10 UTC, Habbie requested changes
Taking just the patch from pdns_recursor.cc does not fix the issue for me, and I don't see why it would..

2021-03-17 15:30 UTC, Habbie commented
The inline TTL calculation was needlessly complex before, and this PR does not make that better; and probably because of that, it manages to miss a case.

Proposal: https://gist.github.com/Habbie/5e8a2ea5187cfe02ec74be8590db538e

2021-03-17 15:37 UTC, Habbie commented
Correction! The inline TTL calculation confused me to the point that I only took one line from the patch instead of two (thus stacking `min()` calls the wrong way). The PR does solve the issue.

However, the PR looks wrong for the case where packet cache TTL < packet cache servfail TTL. My proposed version covers that, and improves readability.

2021-03-17 15:40 UTC, omoerbeek commented
> Correction! The inline TTL calculation confused me to the point that I only took one line from the patch instead of two (thus stacking `min()` calls the wrong way). The PR does solve the issue.
> 
> However, the PR looks wrong for the case where packet cache TTL < packet cache servfail TTL. My proposed version covers that, and improves readability.

Thers is code to ensure `packetcacheservfailttl` <= `s_packetcachettl` (line 4603)

2021-03-17 15:41 UTC, Habbie commented
> There is code to ensure `packetcacheservfailttl` <= `s_packetcachettl` (line 4603)

Right! Then your version was, in fact, correct. We can take my readability improvements, and we could decide to leave what now appears to be an additional belt/suspender from me in, or take that out.

2021-03-17 15:48 UTC, Habbie approved these changes

2021-03-17 20:37 UTC, Habbie commented
> test does not like the new safety belt

I pushed a fix for the test; please check the comment (and the change); we need to squash things so we don't end up with a broken commit in our history.

2021-03-18 08:17 UTC, rgacogne approved these changes
Looks good to me once the last commits have been squashed!

2021-03-18 08:34 UTC, Habbie commented
Squashed & tested locally once more.

2021-03-18 08:56 UTC, Habbie commented
4 failing checks are unrelated (auth mysql)

2021-03-18 09:46 UTC, Habbie commented
More dnsdist failures.

2021-03-18 09:46 UTC, Habbie commented
```
======================================================================
FAIL: Cache: Cache entry, set backend down, get stale entry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/project/regression-tests.dnsdist/test_Caching.py", line 1086, in testCacheStale
    self.assertEquals(an.ttl, self._staleCacheTTL)
AssertionError: 0 != 60
```

2021-03-18 11:03 UTC, Habbie commented
@rgacogne I'm going to need another review from you :)

2021-03-18 14:20 UTC, rgacogne approved these changes

2021-03-18 14:20 UTC, Habbie commented
Thanks! Squashing again :)

2021-03-18 20:25 UTC, merged