rec: changelog and secpoll for rec 4.3.7
PowerDNS/pdns pull request #10195
Opened 2021-03-19 10:25 UTC by omoerbeek

### Short description

Plus a bonus dangling reference in docs fix.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-03-19 12:45 UTC, rgacogne approved these changes

2021-03-22 12:24 UTC, Habbie requested changes

2021-03-22 12:24 UTC, Habbie commented on pdns/recursordist/docs/changelog/4.3.rst
> +  :released: 22th of March 2021
```suggestion
  :released: 22nd of March 2021
```

2021-03-22 13:06 UTC, Habbie approved these changes

2021-03-22 13:07 UTC, merged