Make QClass a class, including toString() method
PowerDNS/pdns pull request #10245
Opened 2021-03-30 12:53 UTC by omoerbeek

### Short description

And start using it in a few places.
Fixes #7389
### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-03-31 07:31 UTC, omoerbeek commented
I'm not 100% happy yet, pondering if it should be better to have the constants actually be of type QClass instead of the intenral enum type...

2021-04-09 07:13 UTC, Habbie requested changes
I like all the code changes that follow from this change (like function arguments having type `QClass`). Some other notes though.

2021-04-09 07:14 UTC, Habbie commented
> I'm not 100% happy yet, pondering if it should be better to have the constants actually be of type QClass instead of the internal enum type...

I tried having an opinion on this but I failed.

2021-04-09 07:41 UTC, omoerbeek commented on pdns/qtype.cc
> +const std::string QClass::toString() const
I'd rather go to opposite way and name a `toString` like methods `toString` so I don't have to think what the name is for a method to get a string representation of an object. It really would be nice if all our classes that are potentially loggable should use the same method name, and I think 'getName' is not the right name.

2021-04-09 07:43 UTC, Habbie commented on pdns/qtype.cc
> +const std::string QClass::toString() const
Right! The point was consistency, I think I also prefer `toString()`, then it's consistent with `DNSName` too. Feel free to leave that rename on QType for a separate PR though.

2021-04-09 13:03 UTC, Habbie approved these changes

2021-04-09 13:04 UTC, merged