auth: replace domain-metadata-cache-ttl by zone-metadata-cache-ttl
PowerDNS/pdns pull request #10424
Opened 2021-05-18 19:44 UTC by mind04

### Short description
and some domain -> zone in the settings descriptions and settings.rst

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-05-18 19:55 UTC, klaus-nicat commented
Basically this makes sense. But if you go this way you also have to change the table name - TTL setting and table name IMO belong together. Or you will end up with lots renaming and have not renamed all (then better do not rename at all).

2021-05-19 10:54 UTC, Habbie commented
> Basically this makes sense. But if you go this way you also have to change the table name - TTL setting and table name IMO belong together. Or you will end up with lots renaming and have not renamed all (then better do not rename at all).

We cannot fix everything at once. The API, for example, has always called it zone metadata. We will get there eventually.

2021-05-19 12:14 UTC, Habbie requested changes
one change requested, otherwise good!

2021-05-19 12:14 UTC, Habbie commented on pdns/pdnsutil.cc
> +            throw PDNSException("Failed to feed zones metadata");
```suggestion
            throw PDNSException("Failed to feed zone metadata");
```

2021-05-19 14:06 UTC, Habbie approved these changes

2021-05-19 14:06 UTC, merged