auth: remove pubsuffix
PowerDNS/pdns pull request #10507
Opened 2021-06-18 14:13 UTC by Habbie

### Short description
fixes #9891

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2021-06-21 18:55 UTC, mind04 requested changes
please remove effective_tld_names.dat (and the licence) from pdns/builder-support/debian/authoritative/debian-buster as well.

2021-06-22 13:35 UTC, Habbie commented
> please remove effective_tld_names.dat (and the licence) from pdns/builder-support/debian/authoritative/debian-buster as well.

ah thanks! Pushed.

2021-06-22 13:45 UTC, mind04 approved these changes

2021-06-22 14:45 UTC, zeha approved these changes

2021-06-23 11:05 UTC, merged