rec: Keep a count of per rpz (or filter) hits, by default only exported via Prometheus
PowerDNS/pdns pull request #10605
Opened 2021-07-21 08:38 UTC by omoerbeek

This is not finished yet, after #10554 is merged the Prometheus help info should be added
to this branch. The current Prometheus HELP code does not handle multicounter stuff and that PR adds is.

### Short description

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-08-19 07:31 UTC, omoerbeek commented
Example Prometheus output:
```
# TYPE pdns_recursor_policy_hits counter
# HELP pdns_recursor_policy_hits Number of filter or RPZ policy hits
pdns_recursor_policy_hits 10
pdns_recursor_policy_hits{type="filter"} 3
pdns_recursor_policy_hits{type="rpz",policyname="rpz.local"} 5
pdns_recursor_policy_hits{type="rpz",policyname="rpzFile"} 2
```

2021-08-20 10:00 UTC, rgacogne requested changes

2021-08-20 11:11 UTC, omoerbeek commented on pdns/syncres.cc
> +    ++g_stats.policyHits[d_appliedPolicy.getName()];
Yes, you are right. Thanks for spotting this, I have to think a bit how to solve this.

2021-08-20 12:23 UTC, rgacogne approved these changes
Looks good! I'm a bit sad to have to use a lock for policy hits, but I guess we can try a more complicated code using shared lock if we see a noticeable performance impact.

2021-08-20 13:01 UTC, merged