rec: followup to Prometheus-friendly histograms (#10122)
PowerDNS/pdns pull request #10663
Opened 2021-08-24 07:51 UTC by omoerbeek

Process feedback from @johnhtodd and @wojas : better names and HELP and use a tag to distinguish
ipv4 and ipv6 for the new Prometheus-friendly histograms.

Followup to #10122 

### Short description

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

Example output:
```

# TYPE pdns_recursor_cumul_authanswers_seconds histogram
# HELP pdns_recursor_cumul_authanswers_seconds histogram of answer times of authoritative servers
pdns_recursor_cumul_authanswers_seconds_count 45
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.01"} 12
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.01"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.1"} 27
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.1"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="1"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="1"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="10"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="10"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.02"} 21
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.02"} 3
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.2"} 31
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.2"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="2"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="2"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.05"} 27
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.05"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.5"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.5"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="5"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="5"} 9
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="+Inf"} 36
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="+Inf"} 9
pdns_recursor_cumul_authanswers_seconds_sum 2.79109
# TYPE pdns_recursor_cumul_clientanswers_seconds histogram
# HELP pdns_recursor_cumul_clientanswers_seconds histogram of our answer times to clients
pdns_recursor_cumul_clientanswers_seconds_count 7
pdns_recursor_cumul_clientanswers_seconds_bucket{le="1e-05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="2e-05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="5e-05"} 2
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0001"} 2
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0002"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0005"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.001"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.002"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.005"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.01"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.02"} 3
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.05"} 4
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.1"} 5
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.2"} 5
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.5"} 5
pdns_recursor_cumul_clientanswers_seconds_bucket{le="1"} 5
pdns_recursor_cumul_clientanswers_seconds_bucket{le="2"} 7
pdns_recursor_cumul_clientanswers_seconds_bucket{le="5"} 7
pdns_recursor_cumul_clientanswers_seconds_bucket{le="10"} 7
pdns_recursor_cumul_clientanswers_seconds_bucket{le="+Inf"} 7
pdns_recursor_cumul_clientanswers_seconds_sum 2.69777
```

2021-09-09 14:53 UTC, rgacogne approved these changes

2021-09-13 06:25 UTC, wojas requested changes
The `pdns_recursor_cumul_authanswers_seconds_count ` and `_sum` also need the `ipversion` labels, otherwise they are not individually usable as histograms.

2021-09-14 06:43 UTC, omoerbeek commented
> The `pdns_recursor_cumul_authanswers_seconds_count ` and `_sum` also need the `ipversion` labels, otherwise they are not individually usable as histograms.

Do they need both the unlabeled (sum of sums) and a labeled version or only a labeled version?

2021-09-14 07:25 UTC, wojas commented
Just the ones with labels. If you want both combined, you can aggregate them.

Example from the Django exporter:

```
django_http_requests_latency_seconds_by_view_method_bucket{le="0.005",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.01",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.025",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.05",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.075",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.1",method="GET",view="admin:index"} 0.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.25",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.5",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="0.75",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="1.0",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="2.5",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="5.0",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="7.5",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="10.0",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_bucket{le="+Inf",method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_count{method="GET",view="admin:index"} 1.0
django_http_requests_latency_seconds_by_view_method_sum{method="GET",view="admin:index"} 0.1244468999793753
```

2021-09-14 07:44 UTC, omoerbeek commented
```
# TYPE pdns_recursor_cumul_authanswers_seconds histogram
# HELP pdns_recursor_cumul_authanswers_seconds histogram of answer times of authoritative servers
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v4"} 49
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v6"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.001"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.002"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.005"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.01"} 20
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.01"} 0
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.02"} 29
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.02"} 8
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.05"} 37
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.05"} 13
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.1"} 37
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.1"} 13
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.2"} 41
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.2"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="0.5"} 42
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="0.5"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="1"} 42
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="1"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="2"} 49
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="2"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="5"} 49
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="5"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="10"} 49
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="10"} 14
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v4",le="+Inf"} 49
pdns_recursor_cumul_authanswers_seconds_bucket{ipversion="v6",le="+Inf"} 14
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v4"} 13.44
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v6"} 0.431574
# TYPE pdns_recursor_cumul_clientanswers_seconds histogram
# HELP pdns_recursor_cumul_clientanswers_seconds histogram of our answer times to clients
pdns_recursor_cumul_clientanswers_seconds_count 5
pdns_recursor_cumul_clientanswers_seconds_bucket{le="1e-05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="2e-05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="5e-05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0001"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0002"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.0005"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.001"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.002"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.005"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.01"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.02"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.05"} 0
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.1"} 1
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.2"} 1
pdns_recursor_cumul_clientanswers_seconds_bucket{le="0.5"} 1
pdns_recursor_cumul_clientanswers_seconds_bucket{le="1"} 1
pdns_recursor_cumul_clientanswers_seconds_bucket{le="2"} 2
pdns_recursor_cumul_clientanswers_seconds_bucket{le="5"} 4
pdns_recursor_cumul_clientanswers_seconds_bucket{le="10"} 5
```

2021-09-14 12:10 UTC, wojas commented
The last two need to be `_sum`:

```
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v4"} 49
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v6"} 14
...
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v4"} 13.44
pdns_recursor_cumul_authanswers_seconds_count{ipversion="v6"} 0.431574
```

2021-09-14 13:43 UTC, omoerbeek commented
now:
```
pdns_recursor_cumul_authanswers_seconds_sum{ipversion="v4"} 1.16935
pdns_recursor_cumul_authanswers_seconds_sum{ipversion="v6"} 0.847913
```

2021-09-15 07:28 UTC, wojas approved these changes

2021-09-15 07:33 UTC, merged