Rec: proxy by table
PowerDNS/pdns pull request #11396
Opened 2022-03-07 12:40 UTC by omoerbeek

### Short description

A way to internally used a mapped adres as the source address for a query.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [X] documented the code
- [X] added or modified regression test(s)
- [ ] added or modified unit test(s)

2022-03-11 11:59 UTC, rgacogne requested changes
One nit but the PR seems very nice!

2022-03-11 11:59 UTC, rgacogne commented on pdns/pdns_recursor.cc
> +static string* doProcessUDPQuestion(const std::string& question, const ComboAddress& fromaddr, const ComboAddress& destaddr, ComboAddress source, ComboAddress destination, const ComboAddress& unmappe
A comment about `unmappedSource` would be nice: "the address we assume the query was sent from, before any remapping but after proxy protocol processing"?

2022-03-11 11:59 UTC, rgacogne commented on pdns/recursordist/rec-main.cc
> +    Netmask requestorNM(remote, unmappedRemote.sin4.sin_family == AF_INET ? luaconfsLocal->protobufMaskV4 : luaconfsLocal->protobufMaskV6);
```suggestion
    Netmask requestorNM(remote, remote.sin4.sin_family == AF_INET ? luaconfsLocal->protobufMaskV4 : luaconfsLocal->protobufMaskV6);
```

2022-03-11 11:59 UTC, rgacogne commented on pdns/recursordist/rec-tcp.cc
>      if (t_allowFrom && !t_allowFrom->match(&addr) && !fromProxyProtocolSource) {
Not directly related to this PR but the ACL check seems wasteful when `fromProxyProtocolSource` is true?

2022-03-16 14:42 UTC, omoerbeek commented
@neilcook This is now updated as discussed last Friday

2022-03-16 15:45 UTC, neilcook commented
So as I understand it, with the changes, Lua will still see the original IP address? Actually it might be good to have something that explains where the original address is used and where the mapped address is used?

2022-03-17 10:17 UTC, rgacogne requested changes
Code looks good, a few nits in the comments and documentation.

2022-03-17 10:17 UTC, rgacogne commented on pdns/pdns_recursor.cc
> +// mappedSource: the address we assume the query is coming from, after proxy protocol processing and table based mapping
```suggestion
// mappedSource: the address we assume the query is coming from. Differs from source if table based mapping has been applied
```

2022-03-17 10:17 UTC, rgacogne commented on pdns/pdns_recursor.cc
> +  dc->setMappedSource(mappedSource); // the address we assume the query is comming after proxy protocol and table bases mapping
```suggestion
  dc->setMappedSource(mappedSource); // the address we assume the query is coming from. Differs from source if table-based mapping has been applied
```

2022-03-17 10:17 UTC, rgacogne commented on pdns/recursordist/docs/lua-config/proxymapping.rst
> +Starting with version 4.7.0, the PowerDNS Recursor has the ability to map source IP addresses to an alternative address.
```suggestion
Starting with version 4.7.0, the PowerDNS Recursor has the ability to map source IP addresses to alternative addresses, which is for example useful when some clients reach the recursor via a reverse-proxy.
```

2022-03-17 10:17 UTC, rgacogne commented on pdns/recursordist/rec-tcp.cc
> +      dc->setMappedSource(conn->d_mappedSource); // the address we assume the query is comming from after table based mapping
```suggestion
      dc->setMappedSource(conn->d_mappedSource); // the address we assume the query is coming from after table based mapping
```

2022-03-17 10:17 UTC, rgacogne commented on regression-tests.recursor-dnssec/test_ProxyByTable.py
> +    _confdir = 'ProxyByTable'
```suggestion
    """
    This test makes sure that we correctly use the proxy-mapped address during the ACL check
    """
    _confdir = 'ProxyByTable'
```

2022-03-18 11:24 UTC, omoerbeek commented
@rgacogne and @neilcook I extended the docs. Review appreciated!

2022-03-18 13:55 UTC, neilcook commented
> @rgacogne and @neilcook I extended the docs. Review appreciated!

Docs are much clearer now, and LGTM.

2022-03-21 10:12 UTC, rgacogne approved these changes
Awesome work with the documentation, Otto! A couple remaining nits but nothing quite important.

2022-03-21 10:12 UTC, rgacogne commented on pdns/recursordist/rec-tcp.cc
> +      dc->setMappedSource(conn->d_mappedSource); // the address we assume the query is comming from after table based mapping
Still wrong, I think?

2022-03-21 10:12 UTC, rgacogne commented on pdns/recursordist/docs/lua-config/proxymapping.rst
> +
Very nice! It might be good to also document which address will be logged in our internal logs?

2022-03-21 10:35 UTC, omoerbeek commented
Comments processed and squashed. Once green I'll merge.

2022-03-21 11:35 UTC, merged