[clang-tidy] Use nullptr explicitly and initialize directly.
PowerDNS/pdns pull request #11968
Opened 2022-09-17 12:48 UTC by darnuria

### Short description
An other clang-tidy in `pdns_utils` nullptr + initialize.
Moved the comments upper to avoid depassing 80char limit.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code unit tested same issue deadlock like in !11966
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2022-09-19 08:39 UTC, rgacogne approved these changes

2022-09-19 08:41 UTC, omoerbeek requested changes
A few nits: for such simple boolean expressions, the extra parentheses add nothing.

2022-09-19 08:41 UTC, omoerbeek commented on pdns/pdnsutil.cc
> +    done = ((suppliedrecords != nullptr) || !sd.db->doesDNSSEC());
Not a big fan of the extra parentheses.

2022-09-19 08:41 UTC, omoerbeek commented on pdns/pdnsutil.cc
> +    if( ! ok && (suppliedrecords == nullptr) ) {
Not a big fan of the extra parentheses.

2022-09-19 08:41 UTC, omoerbeek commented on pdns/pdnsutil.cc
> +  if(!B.getDomainInfo(zone, di, false) || (di.backend == nullptr)) {
Not a big fan of the extra parentheses.

2022-09-19 08:41 UTC, omoerbeek commented on pdns/pdnsutil.cc
> +  if(!B.getDomainInfo(zone, di) || (di.backend == nullptr)) {
Not a big fan of the extra parentheses.

2022-09-19 12:02 UTC, darnuria commented
Thanks for review the extra parentheses comes from the clang-tidy suggestion will push a change right now.

2022-09-19 13:14 UTC, omoerbeek approved these changes

2022-09-24 18:41 UTC, darnuria commented
Squashed and rebased on top of master.

2022-11-06 12:47 UTC, darnuria commented
Same did a rebase against master and bump.

2022-11-07 09:53 UTC, rgacogne approved these changes

2022-11-28 10:50 UTC, merged