auth lmdb: make outgoing notifications work
PowerDNS/pdns pull request #12282
Opened 2022-12-06 16:42 UTC by Habbie

### Short description

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2022-12-06 18:10 UTC, mind04 approved these changes

2022-12-07 08:30 UTC, mind04 requested changes
updateHash() is using di.id as well. Please do something like this:
```
@@ -1107,13 +1107,16 @@ void LMDBBackend::getUpdatedMasters(vector<DomainInfo>& updatedDomains, std::uno
       continue; // Producer fresness check is performed elsewhere
     }
 
+    di = *iter;
+    di.id = iter.getID();
+
     if (!iter->catalog.empty()) {
       ci.fromJson(iter->options, CatalogInfo::CatalogType::Producer);
-      ci.updateHash(catalogHashes, *iter);
+      ci.updateHash(catalogHashes, di);
     }
 
-    di = *iter;
     if (getSerial(di) && di.serial != di.notified_serial) {
+      di.backend = this;
       updatedDomains.emplace_back(di);
     }
   }
```
Sorry for not catching this in my initial review.

2022-12-07 12:57 UTC, Habbie commented
amended, thanks!

2022-12-08 08:49 UTC, mind04 approved these changes

2022-12-08 09:12 UTC, merged