Misc additions and changes to CI documentation generation
PowerDNS/pdns pull request #12448
Opened 2023-01-20 15:43 UTC by fredmorcos

### Short description
- Add short commit hash to html doc artifacts that are uploaded to GH.
- Always build and GH artifact upload documentation PDFs since installing their deps doesn't take that much time anymore.
- Add the product (auth/rec/dnsdist) name to the html doc artifacts.

### Checklist
I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-01-23 09:25 UTC, Habbie commented
can you add the hash to the pdf names too?

2023-01-23 13:27 UTC, fredmorcos commented
> can you add the hash to the pdf names too?

Done.

2023-01-27 09:40 UTC, fredmorcos commented
Can we merge this?

2023-01-27 09:53 UTC, rgacogne reviewed
So the changes look good to me, but I feel a bit out my depth so I would not mind someone else having a look before merging this.

2023-01-27 14:06 UTC, Habbie requested changes
one request, otherwise good!

2023-01-27 14:06 UTC, Habbie commented on tasks.py
> +    c.run(f"rsync -crv --no-p --chmod=g=rwX --exclude '*~' ./docs/_build/{product}-html-docs.tar.bz2 {username}@{docs_host}:{directory}")
```suggestion
    c.run(f"rsync -crv --no-p --chmod=g=rwX --exclude '*~' ./docs/_build/{product}-html-docs.tar.bz2 {username}@{docs_host}:{directory}/html-docs.tar.bz2")
```

2023-01-27 14:34 UTC, Habbie approved these changes

2023-02-02 14:59 UTC, fredmorcos commented
Reminder to merge 😄

2023-02-02 15:00 UTC, merged

2023-02-02 16:19 UTC, rgacogne commented
This appears to be failing: https://github.com/PowerDNS/pdns/actions/runs/4076304690/jobs/7023858077

2023-02-02 16:21 UTC, rgacogne commented
```
Run inv ci-docs-upload-master --docs-host="${DOCS_HOST}" --pdf="PowerDNS-Authoritative.pdf" --username="docs_powerdns_com" product="auth" --directory="/${AUTH_DOCS_DIR}/"
Warning: Permanently added the ECDSA host key for IP address '188.166.104.92' to the list of known hosts.
rsync: change_dir "/home/runner/work/pdns/pdns//./docs/_build/html-docs" failed: No such file or directory (2)

rsync -crv --delete --no-p --chmod=g=rwX --exclude '*~' ./docs/_build/html-docs/ docs_powerdns_com@web1.powerdns.com://authoritative/
  sending incremental file list
  
  rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
  sent 32 bytes  received 12 bytes  17.60 bytes/sec
  total size is 0  speedup is 0.00
  Error: Process completed with exit code 23.
  ```

2023-02-02 18:53 UTC, fredmorcos commented
> This appears to be failing: https://github.com/PowerDNS/pdns/actions/runs/4076304690/jobs/7023858077

Fix in #12503