Builder-dispatch: Generate provenance for built artifacts
PowerDNS/pdns pull request #12556
Opened 2023-02-16 10:59 UTC by rgacogne

### Short description

This PR is a first step into better SLSA-compliance. It makes a few changes to our builder-dispatch workflow:
- generate sha256 hashes for all the artifacts generated (source tarballs and package tarballs) by the build process
- generate intoto provenance attestation for these artifacts using the generic provenance generator (https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic) 

At the moment the provenance attestation is only accessible as an action artifact, and is not uploaded along the other artifacts, which is something we might want to do.

The attestation states that the artifacts were generated on a GitHub action runner, and with which exact workflow and parameters.

The attestation can be visualized via `$ cat multiple.intoto.jsonl | jq -r '.payload' | base64 -d | jq`:
```json
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "./built_pkgs/dnsdist/1.8.0-alpha0.2615.master.g26a500c3a/dnsdist-1.8.0-alpha0.2615.master.g26a500c3a-el-7.tar.bz2",
      "digest": {
        "sha256": "24de79c06d31b5f1ae9e1c94dfeb8320bbd0586e51f178ffa70a788eb3796cb8"
      }
    },
    {
      "name": "./built_pkgs/dnsdist/1.8.0-alpha0.2615.master.g26a500c3a/dnsdist-1.8.0-alpha0.2615.master.g26a500c3a.tar.bz2",
      "digest": {
        "sha256": "1fbe457efc007ffdcd742e6081ee932a46b3e6b8c6a9dc513978755897e4c9ec"
      }
    }
  ],
  "predicate": {
    "builder": {
      "id": "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.4.0"
    },
    "buildType": "https://github.com/slsa-framework/slsa-github-generator/generic@v1",
    "invocation": {
      "configSource": {
        "uri": "git+https://github.com/rgacogne/pdns@refs/heads/generate-provenance",
        "digest": {
          "sha1": "7d225ddae9979017c1ce1c4bedec4746d57461d8"
        },
        "entryPoint": ".github/workflows/builder-dispatch.yml"
      },
      "parameters": {
        "event_inputs": {
          "is_release": "NO",
          "os": "el-7",
          "product": "dnsdist",
          "ref": "master"
        }
      },
      "environment": {
        "github_actor": "rgacogne",
        "github_actor_id": "1086257",
        "github_base_ref": "",
        "github_event_name": "workflow_dispatch",
        "github_event_payload": {
          "inputs": {
            "is_release": "NO",
            "os": "el-7",
            "product": "dnsdist",
            "ref": "master"
          },
          "ref": "refs/heads/generate-provenance",
          "repository": {
            "allow_forking": true,
            "archive_url": "https://api.github.com/repos/rgacogne/pdns/{archive_format}{/ref}",
            "archived": false,
            "assignees_url": "https://api.github.com/repos/rgacogne/pdns/assignees{/user}",
            "blobs_url": "https://api.github.com/repos/rgacogne/pdns/git/blobs{/sha}",
            "branches_url": "https://api.github.com/repos/rgacogne/pdns/branches{/branch}",
            "clone_url": "https://github.com/rgacogne/pdns.git",
            "collaborators_url": "https://api.github.com/repos/rgacogne/pdns/collaborators{/collaborator}",
            "comments_url": "https://api.github.com/repos/rgacogne/pdns/comments{/number}",
            "commits_url": "https://api.github.com/repos/rgacogne/pdns/commits{/sha}",
            "compare_url": "https://api.github.com/repos/rgacogne/pdns/compare/{base}...{head}",
            "contents_url": "https://api.github.com/repos/rgacogne/pdns/contents/{+path}",
            "contributors_url": "https://api.github.com/repos/rgacogne/pdns/contributors",
            "created_at": "2015-11-03T10:29:53Z",
            "default_branch": "master",
            "deployments_url": "https://api.github.com/repos/rgacogne/pdns/deployments",
            "description": "PowerDNS",
            "disabled": false,
            "downloads_url": "https://api.github.com/repos/rgacogne/pdns/downloads",
            "events_url": "https://api.github.com/repos/rgacogne/pdns/events",
            "fork": true,
            "forks": 1,
            "forks_count": 1,
            "forks_url": "https://api.github.com/repos/rgacogne/pdns/forks",
            "full_name": "rgacogne/pdns",
            "git_commits_url": "https://api.github.com/repos/rgacogne/pdns/git/commits{/sha}",
            "git_refs_url": "https://api.github.com/repos/rgacogne/pdns/git/refs{/sha}",
            "git_tags_url": "https://api.github.com/repos/rgacogne/pdns/git/tags{/sha}",
            "git_url": "git://github.com/rgacogne/pdns.git",
            "has_discussions": false,
            "has_downloads": true,
            "has_issues": false,
            "has_pages": false,
            "has_projects": true,
            "has_wiki": true,
            "homepage": null,
            "hooks_url": "https://api.github.com/repos/rgacogne/pdns/hooks",
            "html_url": "https://github.com/rgacogne/pdns",
            "id": 45459221,
            "is_template": false,
            "issue_comment_url": "https://api.github.com/repos/rgacogne/pdns/issues/comments{/number}",
            "issue_events_url": "https://api.github.com/repos/rgacogne/pdns/issues/events{/number}",
            "issues_url": "https://api.github.com/repos/rgacogne/pdns/issues{/number}",
            "keys_url": "https://api.github.com/repos/rgacogne/pdns/keys{/key_id}",
            "labels_url": "https://api.github.com/repos/rgacogne/pdns/labels{/name}",
            "language": "C++",
            "languages_url": "https://api.github.com/repos/rgacogne/pdns/languages",
            "license": {
              "key": "gpl-2.0",
              "name": "GNU General Public License v2.0",
              "node_id": "MDc6TGljZW5zZTg=",
              "spdx_id": "GPL-2.0",
              "url": "https://api.github.com/licenses/gpl-2.0"
            },
            "merges_url": "https://api.github.com/repos/rgacogne/pdns/merges",
            "milestones_url": "https://api.github.com/repos/rgacogne/pdns/milestones{/number}",
            "mirror_url": null,
            "name": "pdns",
            "node_id": "MDEwOlJlcG9zaXRvcnk0NTQ1OTIyMQ==",
            "notifications_url": "https://api.github.com/repos/rgacogne/pdns/notifications{?since,all,participating}",
            "open_issues": 0,
            "open_issues_count": 0,
            "owner": {
              "avatar_url": "https://avatars.githubusercontent.com/u/1086257?v=4",
              "events_url": "https://api.github.com/users/rgacogne/events{/privacy}",
              "followers_url": "https://api.github.com/users/rgacogne/followers",
              "following_url": "https://api.github.com/users/rgacogne/following{/other_user}",
              "gists_url": "https://api.github.com/users/rgacogne/gists{/gist_id}",
              "gravatar_id": "",
              "html_url": "https://github.com/rgacogne",
              "id": 1086257,
              "login": "rgacogne",
              "node_id": "MDQ6VXNlcjEwODYyNTc=",
              "organizations_url": "https://api.github.com/users/rgacogne/orgs",
              "received_events_url": "https://api.github.com/users/rgacogne/received_events",
              "repos_url": "https://api.github.com/users/rgacogne/repos",
              "site_admin": false,
              "starred_url": "https://api.github.com/users/rgacogne/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/rgacogne/subscriptions",
              "type": "User",
              "url": "https://api.github.com/users/rgacogne"
            },
            "private": false,
            "pulls_url": "https://api.github.com/repos/rgacogne/pdns/pulls{/number}",
            "pushed_at": "2023-02-16T10:27:07Z",
            "releases_url": "https://api.github.com/repos/rgacogne/pdns/releases{/id}",
            "size": 81704,
            "ssh_url": "git@github.com:rgacogne/pdn [...]

2023-02-16 11:00 UTC, Habbie commented
this replaces a big part of #10989 I think?

2023-02-16 11:01 UTC, rgacogne commented
> this replaces a big part of #10989 I think?

It aims to, yes, although I need to make sure I did not forget a very important step (or two) :-)

2023-02-17 14:02 UTC, rgacogne commented
Things to consider:
- would it make sense to extract packages from the tarballs instead of signing the tarball? It would provide attestation for the packages instead which would be better (actually, why are we generating a tarball of packages, I genuinely cannot remember?)
- separate attestations for tarball and perhaps for each package?
- it would be nice to output the list of packages used during the build and their versions, and to include that in the attestation if possible
- pinning dependencies whenever possible would make sense. @wojas mentioned to me that the version of `pdns-builder` is already tied to the version of the repository present in the attestation which is nice.

2023-02-22 10:31 UTC, rgacogne commented
> Things to consider:
> 
>     * would it make sense to extract packages from the tarballs instead of signing the tarball? It would provide attestation for the packages instead which would be better (actually, why are we generating a tarball of packages, I genuinely cannot remember?)
> 
>     * separate attestations for tarball and perhaps for each package?
> 
>     * it would be nice to output the list of packages used during the build and their versions, and to include that in the attestation if possible
> 
>     * pinning dependencies whenever possible would make sense. @wojas mentioned to me that the version of `pdns-builder` is already tied to the version of the repository present in the attestation which is nice.
> 
>     * publishing the attestations along with the source tarball and packages would make sense

It turns out that @pieterlexis got us covered, or at least provided very nice pieces of this puzzle, in `builder/helpers/generate-deb-provenance.py`, `generate-dnf-provenance.py` and `generate-yum-provenance.py` :heart_eyes:

2023-02-24 15:30 UTC, rgacogne commented
>     * would it make sense to extract packages from the tarballs instead of signing the tarball? It would provide attestation for the packages instead which would be better (actually, why are we generating a tarball of packages, I genuinely cannot remember?)

Done, the packages are now extracted.

>     * separate attestations for tarball and perhaps for each package?

Done, we now have one attestation for the source tarball, also including the hash of the packages installed on the target OS used to generate the tarball, plus one attestation per target OS.

>     * it would be nice to output the list of packages used during the build and their versions, and to include that in the attestation if possible

Done, one JSON file is now included in each target OS tarball, containing the list of all installed packages with their versions and hashes (courtesy of Pieter Lexis, to be clear).

>     * pinning dependencies whenever possible would make sense. @wojas mentioned to me that the version of `pdns-builder` is already tied to the version of the repository present in the attestation which is nice.

Not done at the moment, but can be done independently.

>     * publishing the attestations along with the source tarball and packages would make sense

Not done, as it might only make sense for actual releases. Perhaps we can automate that if they set up automatic building when a tag is pushed.

2023-03-10 16:51 UTC, rgacogne commented
Quick check based on https://slsa.dev/spec/v0.1/requirements

Source requirements
===================

- Version controlled: OK
- Verified history: OK
- Retained indefinitely: OK
- Two-person reviewed: **NOK** (only the reviewer/merger is a trusted person. We would need to have two different reviewers to go to L4)

Build requirements
==================

- Scripted build: OK
- Build service: OK
- Build as code: OK
- Ephemeral environment: OK
- Isolated: **NOK** (we might need to stop using caching for releases to go to L3 and L4)
- Parameterless: **NOK** (we might need to build automatically when a tag is pushed without any external parameter to reach L4)
- Hermetic: **NOK** (we would need to pin everything we install to go to L4)
- Reproducible: OK

Provenance requirements
=======================

- Available: OK
- Authenticated: OK
- Service generated: OK
- Non-falsifiable: OK
- Dependencies complete: **NOK** (we do record system packages with their version and hash, but we would likely need to do the same for python dependencies (or pin them) to reach L4)

- Identifies artifact: OK
- Identifies builder: OK
- Identifies build instructions: OK
- Identifies source code: OK
- Identifies entry point: OK
- Includes all build parameters: **NOK** (see Parameterless)
- Includes all transitive dependencies: **NOK** (see Dependencies complete)
- Includes reproducible info: OK
- Includes metadata: OK

If I'm not mistaken, fixing the `Isolated` requirement would get us to L3. L4 would require a bit more work, and the two-persons reviewed requirement would be quite some hassle.

2023-05-04 14:05 UTC, rgacogne commented
- Rebased on master
- Added a reusable workflow to build packages when a tag is pushed
- Refactored builder-dispatch to use the reusable workflow as well

2023-05-04 14:11 UTC, rgacogne commented
With the new changes, if I'm not mistaken:

Source requirements
===================

- Version controlled: OK
- Verified history: OK
- Retained indefinitely: OK
- Two-person reviewed: **NOK** (only the reviewer/merger is a trusted person. We would need to have two different reviewers to go to L4)

Build requirements
==================

- Scripted build: OK
- Build service: OK
- Build as code: OK
- Ephemeral environment: OK
- Isolated: OK (we do not use caching when building packages)
- Parameterless: OK (we do not take parameters when we build from a tag)
- Hermetic: **NOK** (we would need to pin everything we install to go to L4)
- Reproducible: OK

Provenance requirements
=======================

- Available: OK
- Authenticated: OK
- Service generated: OK
- Non-falsifiable: OK
- Dependencies complete: **NOK** (we do record system packages with their version and hash, but we would likely need to do the same for python dependencies (or pin them) to reach L4)

- Identifies artifact: OK
- Identifies builder: OK
- Identifies build instructions: OK
- Identifies source code: OK
- Identifies entry point: OK
- Includes all build parameters: OK
- Includes all transitive dependencies: **NOK** (see Dependencies complete)
- Includes reproducible info: OK
- Includes metadata: OK

2023-06-27 10:29 UTC, Habbie commented
> Parameterless: OK (we do not take parameters when we build from a tag)

tag pushes don't cause builds yet, but they could (Pieter's PR has the yaml for it)



> Reproducible: OK

I vaguely recall that sdist might cause today's date to end up in manual pages, which is not terrible, but does mean a difference.

2023-06-27 10:30 UTC, Habbie requested changes
nice work! the OS list will need updating before merge, and there are next steps (build on tag push is the most important one I think), but I think we can merge this

2023-06-27 10:30 UTC, Habbie commented on .github/workflows/builder-dispatch.yml
> +      pkghashes-ubuntu-jammy: ${{ steps.pkghashes.outputs.pkghashes-ubuntu-jammy }}
I was going to say this list a bit inconvenient, but if we want to be parameterless this list is static anyway - just happens to appear twice in this file, which is workable

2023-06-27 12:40 UTC, rgacogne commented
And we should now properly upload the provenance artifacts as well. It's a bit hard for me to actually test that part, though :-/

2023-06-27 13:24 UTC, rgacogne commented
I found a way to test most of it, please do not review just yet :)

2023-06-27 14:58 UTC, rgacogne commented
@Habbie I did not manage to test everything, especially the part involving the per-repository secrets, but I did test most of the other parts now and fixed a few bugs, I believe this is ready for review!

2023-06-27 15:04 UTC, Habbie approved these changes
great refactor, great work!

2023-06-28 08:58 UTC, merged