auth: harmonize *xfr log messages
PowerDNS/pdns pull request #12565
Opened 2023-02-17 21:44 UTC by jsoref

### Short description

Logs will typically have:

```
AXFR-out zone '<ZONE>', client '<ipv6>', transfer initiated
AXFR-out zone '<ZONE>', client '[<ipv6>]:<PORT>', allowed: client IP is in allow-axfr-ips
AXFR-out zone '<ZONE>', client '<ipv6>', AXFR finished
```
it's frustrating that the three lines aren't consistent -- it makes it hard to scan / match up

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2023-02-17 21:51 UTC, jsoref reviewed
Err. I don't understand any of these details. I was copy-pasting. Perhaps it should be `getRemoteStringWithPort`?

2023-02-17 21:51 UTC, jsoref commented on pdns/tcpreceiver.cc
> +  string logPrefix="AXFR-out zone '"+target.toLogString()+"', client '"+q->getInnerRemote().toStringWithPort()+"', ";
```suggestion
  string logPrefix="AXFR-out zone '"+target.toLogString()+"', client '"+q->getRemoteStringWithPort()+"', ";
```

2023-02-17 21:51 UTC, jsoref commented on pdns/tcpreceiver.cc
> +  string logPrefix="IXFR-out zone '"+q->qdomain.toLogString()+"', client '"+q->getInnerRemote().toStringWithPort()+"', ";
```suggestion
  string logPrefix="IXFR-out zone '"+q->qdomain.toLogString()+"', client '"+q->getRemoteStringWithPort()+"', ";
```

2023-03-08 13:23 UTC, Habbie requested changes

2023-03-08 13:23 UTC, Habbie commented on pdns/tcpreceiver.cc
> +  string logPrefix="AXFR-out zone '"+target.toLogString()+"', client '"+q->getInnerRemote().toStringWithPort()+"', ";
yes

2023-03-08 13:23 UTC, Habbie commented on pdns/tcpreceiver.cc
> +  string logPrefix="IXFR-out zone '"+q->qdomain.toLogString()+"', client '"+q->getInnerRemote().toStringWithPort()+"', ";
yes

2023-08-10 12:12 UTC, Habbie approved these changes

2023-08-10 12:14 UTC, merged