Remove legacy terms from the codebase
PowerDNS/pdns pull request #13023
Opened 2023-07-12 13:55 UTC by mind04

### Short description
Remove legacy terms form the code base.  Round 1

- No api changes
- No backend data storage and scripting changes

Mostly touches auth, but some changes also touch recursor and dnsdist.

Nothing in this pull is final. Feel free to suggest better replacements.

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-09-12 09:49 UTC, rgacogne approved these changes
I only looked at the changes impacting DNSdist and they look good to me, thanks!

2023-10-16 19:47 UTC, Habbie commented
Sorry - this has become conflicted now. If you rebase it, I'll review it soon after.

2023-11-08 13:49 UTC, Habbie requested changes

2023-11-08 13:49 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +std::mutex Bind2Backend::s_autoprimary_config_lock; // protects writes to config file
```suggestion
std::mutex Bind2Backend::s_autosecondary_config_lock; // protects writes to config file
```

2023-11-08 13:49 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +      if (i.d_kind != DomainInfo::Secondary)
because you touch this, I bet clang-tidy is going to ask you to put `{}` around the `continue;`

2023-11-08 13:49 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +  ret << "\t Primarys: " << std::endl;
```suggestion
  ret << "\t Primaries: " << std::endl;
```

2023-11-08 13:49 UTC, Habbie commented on modules/gmysqlbackend/gmysqlbackend.cc
> -    declare(suffix, "info-all-slaves-query", "", "select domains.id, domains.name, domains.type, domains.master, domains.last_check, records.content from domains LEFT JOIN records ON records.domain_i
this will need a note in `docs/upgrading.rst`

2023-11-08 13:49 UTC, Habbie commented on pdns/dnsbackend.hh
> +  //! List all AutoPrimarys, returns false if feature not supported.
```suggestion
  //! List all AutoPrimaries, returns false if feature not supported.
```

2023-11-13 15:38 UTC, Habbie requested changes
amazing work! Two notes, please have a look at them

2023-11-13 15:38 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +  string filename = getArg("autoprimary-destdir") + '/' + domain.toStringNoDot();
this is a breaking change - is it intentional?

2023-11-13 15:38 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +      if (i.d_kind != DomainInfo::Secondary)
handling clang-tidy for this PR is too big a job, that cleanup will have to wait

2023-11-13 15:38 UTC, Habbie commented on .not-formatted
> +./pdns/auth-primarycommunicator.cc
this file still lists `pdns/slavecommunicator.cc`

2023-11-13 19:08 UTC, Habbie approved these changes

2023-11-13 19:22 UTC, Habbie commented on docs/backends/bind.rst
> +Changed in version 4.9.0: This was called ``bind-supermasters`` before 4.9.0.
```suggestion
.. versionchanged:: 4.9.0

  This was called ``bind-supermasters`` before 4.9.0.
```

2023-11-14 09:29 UTC, chbruyand approved these changes
LGTM!

2023-11-14 10:51 UTC, merged