dnsdist: More words on TLS session encryption keys setup and rotation
PowerDNS/pdns pull request #13344
Opened 2023-10-09 08:49 UTC by rgacogne

### Short description

Related to https://github.com/PowerDNS/pdns/issues/13336. 

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-10-19 15:29 UTC, Habbie requested changes
wonderful explanations. Couple of nits

2023-10-19 15:29 UTC, Habbie commented on pdns/dnsdistdist/docs/advanced/tuning.rst
> +For DNS over HTTPS and DNS over TLS, in addition to the advices above we advise reading the :doc:`tls-sessions-management` page to know how to improve TLS session resumption ratio, which has a huge i
```suggestion
For DNS over HTTPS and DNS over TLS, in addition to the advice above we suggest reading the :doc:`tls-sessions-management` page to learn how to improve TLS session resumption ratio, which has a huge impact on CPU usage and latency.
```

2023-10-20 07:15 UTC, rgacogne commented
> Couple of nits

Thanks! I have now pushed a new commit fixing them.

2023-10-20 07:17 UTC, rgacogne commented
Rebased on master to fix a spell-checking issue.

2023-11-03 10:24 UTC, Habbie approved these changes

2023-11-03 14:32 UTC, merged