Add Lua function to pick records via name hash
PowerDNS/pdns pull request #13391
Opened 2023-10-18 01:28 UTC by devicenull

### Short description
This adds a Lua function to return a record based on a weighted hash of the DNS record name.  One use case here is to consistently return the same IP address for a particular cache server based on what subdomain is requesting the data.

This is pretty much a copy and paste of pickwhashed

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-11-03 12:19 UTC, Habbie requested changes
great work! I posted a couple of nits

2023-11-03 12:19 UTC, Habbie commented on docs/lua-records/functions.rst
> +    mydomain.example.com    IN    LUA    A ("picknamehashed({                             "
```suggestion
    mydomain.example.com    IN    LUA    A ("picknamehashed({                          "
```

2023-11-03 12:19 UTC, Habbie commented on regression-tests.auth-py/test_LuaRecords.py
> +                'query': dns.message.make_query('test.namehashed.example.org', 'A')
can you put `query` above `expected` in both dicts?

2023-11-03 12:19 UTC, Habbie commented on docs/lua-records/functions.rst
> +    mydomain.example.com    IN    LUA    A ("picknamehashed({                             "
also, perhaps the example makes more sense as a wildcard

2023-11-09 01:43 UTC, devicenull commented
@Habbie What are your thoughts on if you *want* this or not?  For our uses I was able to reimplement this entirely in Lua, and we'll probably go with that instead.

I'm perfectly willing to just close this MR unless you think this is going to be a useful feature for other people going forward.

I'm also willing to spend the time to get this across the line.  I don't have any real strong preferences either way.

2023-11-09 13:16 UTC, Habbie commented
> What are your thoughts on if you _want_ this or not?

_want_ is a very strong word. I think it's a neat feature, it comes with tests, which means it will be easy to maintain/keep, so I'd like to merge this after minor cleanup.

2023-11-30 16:30 UTC, devicenull commented
Code updated :)

2023-12-01 15:32 UTC, Habbie approved these changes

2024-01-23 13:52 UTC, Habbie commented
rebased to fix a conflict

2024-02-06 12:46 UTC, Habbie commented
> rebased to fix a conflict

I did not rebase correctly there. Should be fixed now.

2024-02-09 10:15 UTC, merged