dnsdist: Improve NetmaskGroupRule/SuffixMatchNodeRule, deprecate `makeRule`
PowerDNS/pdns pull request #13500
Opened 2023-11-16 12:40 UTC by rgacogne

### Short description

Fixes https://github.com/PowerDNS/pdns/issues/10158

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-11-16 15:14 UTC, phonedph1 commented
I think the example config shipped might have some of these deprecated forms now.

```
-- addAction({"abuse.example.org.", "xxx."}, PoolAction("abuse"))
-- addAction("192.0.2.0/24", PoolAction("abuse"))
```

2023-11-16 15:34 UTC, rgacogne commented
> I think the example config shipped might have some of these deprecated forms now.
> 
> ```
> -- addAction({"abuse.example.org.", "xxx."}, PoolAction("abuse"))
> -- addAction("192.0.2.0/24", PoolAction("abuse"))
> ```

Good catch, thanks!

2023-12-01 12:03 UTC, omoerbeek requested changes
Some comments on the docs, plus I'd like to see a few testcases for `makeRule` remain, e.g. in a `test_Deprecated.py` file. It would become too easy to break if not tested.

2023-12-05 09:56 UTC, rgacogne commented
> I'd like to see a few testcases for `makeRule` remain, e.g. in a `test_Deprecated.py` file. It would become too easy to break if not tested.

Good idea, done!

2023-12-05 10:01 UTC, omoerbeek approved these changes

2023-12-05 10:02 UTC, merged