rec: prep 5.0.0 rc1
PowerDNS/pdns pull request #13562
Opened 2023-12-05 10:36 UTC by omoerbeek

### Short description

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2023-12-05 10:42 UTC, rgacogne requested changes

2023-12-05 10:42 UTC, rgacogne commented on pdns/recursordist/docs/appendices/EOL.rst
> +The latest release receives correctness, stability and security updates by releasing minor releases.
We might have too many `release` in this sentence, perhaps:
```suggestion
The latest major release train receives correctness, stability and security updates by the way of minor releases.
```

2023-12-05 10:42 UTC, rgacogne commented on pdns/recursordist/docs/changelog/5.0.rst
> +    Document outgoing querycounts better, including a small fix.
```suggestion
    Document outgoing query counts better, including a small fix.
```

2023-12-05 10:42 UTC, rgacogne commented on pdns/recursordist/docs/changelog/5.0.rst
> +    Take into account throttled queries when determining if we had a cachehit.
```suggestion
    Take into account throttled queries when determining if we had a cache hit.
```

2023-12-05 10:42 UTC, rgacogne commented on pdns/recursordist/docs/upgrade.rst
> +  This is a change in behviour compared to previous releases.
```suggestion
  This is a change in behaviour compared to previous releases.
```

2023-12-05 16:47 UTC, neilcook commented on pdns/recursordist/docs/appendices/EOL.rst
> +We support older releases with critical updates for one year after the next following major release.
The word 'next' seems redundant here.
```suggestion
We support older releases with critical updates for one year after the following major release.
```

2023-12-06 09:21 UTC, aerique approved these changes

2023-12-06 09:43 UTC, merged