dnsdist: ChangeLog and secpoll update for 1.8.3
PowerDNS/pdns pull request #13623
Opened 2023-12-14 10:53 UTC by rgacogne

### Short description

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2023-12-14 12:08 UTC, Habbie approved these changes

2023-12-15 09:19 UTC, omoerbeek requested changes

2023-12-15 09:19 UTC, omoerbeek commented on pdns/dnsdistdist/docs/changelog.rst
> +    :tags: Bugs Fixes, DNS over HTTPS
```suggestion
    :tags: Bug Fixes, DNS over HTTPS
```

2023-12-15 09:19 UTC, omoerbeek commented on pdns/dnsdistdist/docs/changelog.rst
> +    :tags: Bugs Fixes
```suggestion
    :tags: Bug Fixes
```

2023-12-15 09:23 UTC, rgacogne commented on pdns/dnsdistdist/docs/changelog.rst
> +    :tags: Bugs Fixes, DNS over HTTPS
Wow, nice catch. Thanks!

2023-12-15 09:26 UTC, omoerbeek approved these changes

2023-12-15 13:04 UTC, merged