rec: add Lua config to YAML settings
PowerDNS/pdns pull request #13819
Opened 2024-02-22 15:05 UTC by omoerbeek

### Short description

This  large PR (53 files changed) allows settings originally defined by Lua config to be incorporated into the YAML settings introduced in 5.0.

One of the reasons this is big:  I had to tear apart the reading (from either Lua or YAML) of the settings and the activating of the settings. Originally those two things were intertwined. Now both method produce a single data structure (still named `LuaConfigItems`) that is fed to a function that activates the settings.

Included `rec_control show-yaml` and `reload-lua-config` support (for the YAML items that originated in Lua, we might add other reloadable settings later.). You can also dump the read config with `pdns_recursor --config`.

Not 100% finished: I need to go through the files one more time and clean things up. Also docs are a bit light. But we do have tests.

PR'ing now to allow people to start playing with it and hopefully provide feedback.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [X] documented the code
- [X] added or modified regression test(s)
- [X] added or modified unit test(s)

2024-05-06 09:59 UTC, rgacogne requested changes
The code looks good and my tests with existing Lua configuration files have been successful. I noted a few small things but nothing big. Impressive work!

2024-05-06 09:59 UTC, rgacogne commented on pdns/recursordist/settings/cxxsupport.cc
> +  dnstap.logResponses = fsc.logQueries;
```suggestion
  dnstap.logResponses = fsc.logResponses;
```

2024-05-06 14:32 UTC, omoerbeek commented on pdns/recursordist/settings/cxxsupport.cc
> +  }
I'll double check this and either fix the code or add a comment.

2024-05-06 14:34 UTC, omoerbeek commented on pdns/recursordist/settings/cxxsupport.cc
> +    rustvalue.u64_val = 24; // XXX
Yes, this is a bit weird. I realized that (hence the XXX) while writing, but now I forgot. Will figure it out.

2024-05-06 15:14 UTC, rgacogne approved these changes

2024-05-06 15:14 UTC, rgacogne commented on pdns/recursordist/settings/cxxsupport.cc
> +    // All for all other values below, the default is either an empty string or an empty vector.
```suggestion
    // And for all other values below, the default is either an empty string or an empty vector.
```

2024-05-07 07:10 UTC, rgacogne approved these changes

2024-05-07 09:32 UTC, merged