Convert remotebackend unit tests to use python
PowerDNS/pdns pull request #13960
Opened 2024-03-20 22:17 UTC by cmouse

### Short description
Change remotebackend to use python unit tests.
Also fixes few minor issues.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [x] added or modified unit test(s)

2024-03-20 22:23 UTC, cmouse commented
Forgot that regression-tests are also in ruby, but that can be done as separate change too if this gets merged.

2024-03-21 13:09 UTC, Habbie commented
'build auth' is failing:

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile

2024-03-25 12:49 UTC, Habbie commented on modules/remotebackend/testrunner.sh
> +   $mode || rv=$? && rv=0
I'm almost certain this will always set rv to 0. Maybe just leave out the `&& rv=0` bit?

2024-04-03 14:03 UTC, fredmorcos approved these changes

2024-04-03 14:03 UTC, fredmorcos commented on modules/remotebackend/testrunner.sh
> +  flock .create_testenv bash -c "python3 -m venv venv; source venv/bin/activate; pip install wheel; pip install -r ${progdir}/requirements.txt"
Perhaps use `&&` instead of `;` here so that we don't overlook errors.

2024-04-03 14:23 UTC, fredmorcos approved these changes

2024-04-03 14:23 UTC, fredmorcos commented on modules/remotebackend/pdns_unittest.py
> +        if args['ip'] in ips:
Perhaps you meant `kwargs`?

2024-04-04 07:57 UTC, cmouse commented
> Also please merge https://github.com/fredmorcos/pdns/tree/remotebackend-python-tests-meson onto this branch before merging. It adapts the meson build for the python unit tests.

Done

2024-04-04 08:34 UTC, fredmorcos approved these changes

2024-04-04 11:30 UTC, Habbie requested changes

2024-04-04 11:30 UTC, Habbie commented on modules/remotebackend/regression-tests/http-backend.py
> +        """Finish one request b instantiating RequestHandlerClass."""
```suggestion
        """Finish one request by instantiating RequestHandlerClass."""
```

2024-04-04 11:30 UTC, Habbie commented on modules/remotebackend/unittest_json.py
> +        """Finish one request b instantiating RequestHandlerClass."""
```suggestion
        """Finish one request by instantiating RequestHandlerClass."""
```

2024-04-04 11:30 UTC, Habbie commented on modules/remotebackend/unittest_post.py
> +        """Finish one request b instantiating RequestHandlerClass."""
```suggestion
        """Finish one request by instantiating RequestHandlerClass."""
```

2024-04-04 11:30 UTC, Habbie commented on modules/remotebackend/unittest_http.py
> +        """Finish one request b instantiating RequestHandlerClass."""
```suggestion
        """Finish one request by instantiating RequestHandlerClass."""
```

2024-04-04 11:31 UTC, Habbie approved these changes

2024-04-04 12:34 UTC, merged