rec: log kern.max_map_count possibly being to low and log a few exceptions (with rate limiting)
PowerDNS/pdns pull request #14185
Opened 2024-05-17 09:34 UTC by omoerbeek

### Short description

- Warn when `kern.max_map_count` is dangerously low
- Fix a few cases where lack of logging could hide bad errors.
- Don't let recursorthead die on exceptions for the pdns-distributes-queries=no case
- Use rate limited logging for the logging in these cases

Not that the rate limited logging is not very smart, it throws all logging calls in one basket.

You might want to see part of the diff with whitespace ignored, it boils down to indenting changes due to an introduce try/catch block.

Marking as Draft, as I have to think a bit if I have the right approach to the rate limiting. Also I might want to split this PR into separate parts. 

Fixes the logging part of #14180 

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2024-05-17 10:52 UTC, rgacogne commented
Do you think it makes sense to export the current number of mappings (number of lines in `/proc/$(pid)/maps` might work)?

2024-05-17 11:30 UTC, omoerbeek commented
> Do you think it makes sense to export the current number of mappings (number of lines in `/proc/$(pid)/maps` might work)?

A bit hesitant, 

> Do you think it makes sense to export the current number of mappings (number of lines in `/proc/$(pid)/maps` might work)?

Might be useful indeed, though we should be careful, I know that in the past producing map info was very expensive (but maybe that was about `smap` ?

2024-05-21 08:37 UTC, omoerbeek commented
Reworked the rate limiting code a bit.
While tetsing, I am seeing `FDMultiplexer::run() is not reentrant!`, which can hapen if the exception hapens in the `run()` method. In that case `d_inrun` is not reset.

2024-05-21 12:24 UTC, rgacogne requested changes
PR looks good, two suggestions

2024-05-21 13:04 UTC, rgacogne approved these changes

2024-05-21 13:08 UTC, omoerbeek commented on pdns/recursordist/rec-main.cc
> +                     "kern.max_map_count", Logging::Loggable(lim), "mapsNeeded", Logging::Loggable(mapsNeeded),
yes, thanks

2024-05-22 11:18 UTC, merged