dnsdist: Fix a race condition with custom Lua web handlers
PowerDNS/pdns pull request #14341
Opened 2024-06-17 10:28 UTC by rgacogne

### Short description

Custom web handlers written in Lua modify the global Lua context, but until now they did not take the lock protecting it so a data race condition was possible.
Reported by TSAN while running our unit tests.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2024-06-17 11:17 UTC, omoerbeek requested changes

2024-06-17 11:17 UTC, omoerbeek commented on pdns/dnsdistdist/dnsdist-web.cc
> +  (*handlers).emplace(std::make_pair(endpoint, WebHandlerContext{std::move(handler), isLua}));
This changes behavior I think: with`[]` an existing entry would be overwritten, with `emplace` that's not the case.

2024-06-18 06:27 UTC, omoerbeek approved these changes
I think you could have used insert_or_assign, but it does not matter much.

2024-06-18 07:35 UTC, rgacogne commented
> I think you could have used insert_or_assign, but it does not matter much.

Yep, but performance doesn't matter here so I decided to keep the change as small as possible :)

2024-06-18 07:35 UTC, merged