dnsdist: Prepare ChangeLog and secpoll for 1.9.5
PowerDNS/pdns pull request #14350
Opened 2024-06-18 09:35 UTC by rgacogne

### Short description

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [ ] compiled this code
- [ ] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2024-06-19 13:56 UTC, omoerbeek approved these changes

2024-06-20 07:40 UTC, Habbie requested changes

2024-06-20 07:40 UTC, Habbie commented on pdns/dnsdistdist/docs/changelog.rst
> +    Prevent a race when calling `registerWebHandler` at runtime
```suggestion
    Prevent a race when calling ``registerWebHandler`` at runtime
```

2024-06-20 07:40 UTC, Habbie commented on pdns/dnsdistdist/docs/changelog.rst
> +    Edit the systemd unit file, `CAP_BPF` is no longer enough
```suggestion
    Edit the systemd unit file, ``CAP_BPF`` is no longer enough
```

2024-06-20 09:41 UTC, Habbie approved these changes

2024-06-20 09:41 UTC, merged