rec: rework the way tcp-in limits is maintained
PowerDNS/pdns pull request #14606
Opened 2024-08-28 13:26 UTC by omoerbeek

### Short description

Current way is "lazy", and done by each thread listening for incoming TCP by removing the fd from the set and adding it back when there is room. This has the consequence that we stop accepting new connections, but the OS maintains a (potentially) large queue of connections that are to be handled by the application. Depending on the details of the OS, they event might be in ESTABLISHED state. I think it makes more sense to keep accepting connections, but close them immediately if we are over the global limit. This is already done for client specific limits and other cases as well.

Refactor a bit while there and introduce a specific counter for the too many incoming TCP connections case.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [X] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2024-08-29 06:43 UTC, rgacogne requested changes

2024-08-29 06:43 UTC, rgacogne commented on pdns/recursordist/RECURSOR-MIB.txt
> +    ::= { stats 152 }
The new metric needs to be added to `recGroup`.

2024-08-29 06:43 UTC, rgacogne commented on pdns/recursordist/docs/metrics.rst
> +number of times an incoming TCP connection was denied because too many connections
```suggestion
number of times an incoming TCP connection was immediately closed because there was already too many open connections
```

2024-08-30 06:59 UTC, omoerbeek commented
I thought a bit more on how this changes behaviour. If we have a short period of too many incoming connections, previously the extra clients would end up being queued for a while by the OS and then processed once the number of connections drops. With this PR, the excess connecting clients will get a connection closed actively and almost immediately. So the behaviour of short bursts above capacity **will** change. We do it like this for client-IP specific connections already (though that limit is not active by default).

2024-09-02 07:59 UTC, rgacogne commented
> We have to decide explicitly if this change is wanted.

As a data point, the new behaviour is what DNSdist has been doing for a long time, and I'm quite happy with it because if there is failure it happens right away, not after a long timeout. But of course YMMV.

2024-09-03 07:42 UTC, omoerbeek commented
With the added upgrade note I think this is good to go.

2024-09-03 07:59 UTC, rgacogne approved these changes
Looks good to me (minus the typo reported by the spell-checker ;))!

2024-09-03 08:46 UTC, merged