rec: dedup records
PowerDNS/pdns pull request #14617
Opened 2024-09-03 11:31 UTC by omoerbeek

### Short description

This deduplicaties records in two places:

1. Records received from authoritative servers
2. Records sent out to clients (only on non-packet cache hits).

When testing this, I encountered a few cases where auths sent duplicate records.
```
dig @ns4.dnsv5.com getui.com txt 
dig @ord.geons.ftw.jiveip.net api.geoip.jive.com txt
dig @dnsd10.chatango.com chatango.com
dig @ns.sotoon53.com yektanet.com txt
dig @ns.viettelidc.com.vn ns9.viettelidc.com.vn
dig @ns1.cdnetdns.net flypgs.com txt
```
Nothing actually breaks if we don't dedup afaik. So it is questionable of we want this part.

But on the client side, this fixes #14120 and maybe other cases I do not know.

The big question is if we want this. Dedupping is fundamentally not cheap, although I tried to optimize the dedup code.

Originally I played with the idea to change the data structure building the reply vector to avoid duplicates, but that requires changes in many places. Still the idea is not completely off the table. 

On the receiving side the dedup internals could also be weaved into the sanitize code, at the cost of increasing complexity. That would avoid the separate dedup() call.

This will remain a draft until I have some some speed measurements and pondered the alternative approaches some more. This PR is mainly to share thoughts.

The test changes are needed as a few of them use duplicate records.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [X] added or modified regression test(s)
- [X] added or modified unit test(s)

2024-10-07 09:59 UTC, rgacogne reviewed
The logic looks good to me. I guess we could try a few more heuristics before actually serializing the content, like checking if we have several records with the same (qtype, qname), but it might not be worth it. Having real-world numbers would indeed be useful.

2024-10-07 09:59 UTC, rgacogne commented on pdns/dnsparser.hh
> +    return record;
If we go forward, we might want to consider a small refactoring to avoid duplicating code between `serialize` and `wireFormatContent`.

2024-10-07 09:59 UTC, rgacogne commented on pdns/shuffle.hh
> +unsigned int dedup(std::vector<DNSRecord>& rrs);
Perhaps `dedupRecords` instead of `dedup`?

2024-10-25 06:50 UTC, omoerbeek commented
Rebased to fix conflict.

2024-10-25 08:50 UTC, omoerbeek commented
Speedtest results:
```
'2 DedupRecords (generate only)' 0.10 seconds: 1230169.1 runs/s, 0.81 us/run
'2 DedupRecords' 0.10 seconds: 504897.9 runs/s, 1.98 us/run
'2 DedupRecords (with dup)' 0.10 seconds: 628577.4 runs/s, 1.59 us/run
'256 DedupRecords (generate only)' 0.10 seconds: 9248.3 runs/s, 108.13 us/run
'256 DedupRecords' 0.10 seconds: 3867.5 runs/s, 258.57 us/run
'256 DedupRecords (with dup)' 0.10 seconds: 3823.4 runs/s, 261.55 us/run
'4096 DedupRecords (generate only)' 0.11 seconds: 561.7 runs/s, 1780.35 us/run
'4096 DedupRecords' 0.10 seconds: 241.7 runs/s, 4137.49 us/run
'4096 DedupRecords (with dup)' 0.10 seconds: 239.3 runs/s, 4178.26 us/run
```

The measured slowdown is about 2.5 and is uniform over the various test case sizes.

So the dedupping takes time as expected, but for the already pretty extreme case of 256, records, its absolute value is not a lot compared to the expected network latency. For the 4096 case we spent time that comes closer to the expected network latency.

2024-10-25 08:56 UTC, paddg commented
Can we rule out that deduping is an attack vector?

2024-10-25 09:05 UTC, omoerbeek commented
> Can we rule out that deduping is an attack vector?

Not completely, in the extreme case spending even a few CPU ms on a single auth result is quite a lot.

2024-10-25 10:00 UTC, paddg commented
> Not completely, in the extreme case spending even a few CPU ms on a single auth result is quite a lot.

Are you considering an on/off switch for it?

2024-10-25 10:02 UTC, omoerbeek commented
> > Not completely, in the extreme case spending even a few CPU ms on a single auth result is quite a lot.
> 
> Are you considering an on/off switch for it?

Yes, that would be one of the options. Another alternative would be to not do the dedupping on large answers as we already refuse to cache them anyway.

2024-11-04 08:23 UTC, omoerbeek commented
> The logic looks good to me. I guess we could try a few more heuristics before actually serializing the content, like checking if we have several records with the same (qtype, qname), but it might not be worth it. Having real-world numbers would indeed be useful.

I played a bit with a pre-scan on qtype and name only, but saw no speedup

2024-12-24 09:13 UTC, rgacogne requested changes
The general logic and the places were it is applied look good to me.

2024-12-24 09:13 UTC, rgacogne commented on pdns/recursordist/pdns_recursor.cc
> +#ifdef notyet
This might warrant a comment, at the very least :)

2024-12-24 09:13 UTC, rgacogne commented on pdns/shuffle.cc
> +  // This function tries to avoid unneccesary work
```suggestion
  // This function tries to avoid unnecessary work
```

2024-12-24 09:13 UTC, rgacogne commented on pdns/shuffle.cc
> +  // you call it on a large vector muliple times.
```suggestion
  // you call it on a large vector multiple times.
```

2024-12-24 09:13 UTC, rgacogne commented on pdns/speedtest.cc
> +    }
Would it make sense to do this in the constructor instead, to get the initial steps out of the timed computation?

2025-01-07 08:49 UTC, omoerbeek commented on pdns/speedtest.cc
> +    }
I initially did not do that as `operator()()` must be `const`, and `dedup` modifies the vector. A middle ground would be to copy the vec constructed in the ct and operator on that one.

2025-01-07 08:52 UTC, rgacogne commented on pdns/speedtest.cc
> +    }
Oh, right! The middle ground looks good indeed.

2025-01-09 15:00 UTC, rgacogne commented on pdns/speedtest.cc
> +    }
The new version looks good, note that I still have a few comments that have not been addressed as far as I can tell.

2025-01-10 07:04 UTC, omoerbeek commented on pdns/speedtest.cc
> +    }
Hmm, I could have sworn I did the other ones as well, will fix.

2025-01-10 09:13 UTC, rgacogne approved these changes

2025-01-10 09:13 UTC, merged