dnsdist: add elapsed time to dq object
PowerDNS/pdns pull request #14850
Opened 2024-11-18 22:34 UTC by phonedph1

### Short description
FFI seems to have this already.

Not sure if there is a reason not to include it in the normal Lua bindings?

Use case: want to easily check how much time has been spent so far, to decide if query should be replayed or not. 

```Lua
function result(dq)
        warnlog("query elapsed time is " .. dq:getElapsedUs() .. " us")
 
        return DNSResponseAction.None
end
 

addAction(AllRule(), LuaAction(result))
addResponseAction(AllRule(),LuaResponseAction(result))

addLocal("127.0.0.1:5454")
newServer({address="8.8.8.8"})
```

```
query elapsed time is 69.56 us
query elapsed time is 34759.856 us
```

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [x] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)
- [ ]  checked that this code was merged to master

2024-11-19 08:34 UTC, rgacogne requested changes
Thanks a lot for this PR, it looks very good to me! I have one tiny nit in the documentation part, but we could merge this as it is and fix it later.

2024-11-19 08:34 UTC, rgacogne commented on pdns/dnsdistdist/docs/reference/dq.rst
> +  .. method:: DNSQuestion::getElapsedUs -> double
We try to sort the methods alphabetically (you know the difference between theory and practice, right?), so would you mind moving this entry just below `getEDNSOptions`?

2024-11-19 08:35 UTC, rgacogne commented
Marking this PR as a candidate for a backport to 1.9.x since it is very self-contained and could be useful there.

2024-11-20 23:09 UTC, phonedph1 commented
moved the docs up...

2024-11-21 08:12 UTC, rgacogne approved these changes
Thanks a lot, much appreciated!

2024-11-21 08:28 UTC, merged