rec: store authority recs and signatures as shared pointers to const data
PowerDNS/pdns pull request #14985
Opened 2024-12-18 09:17 UTC by omoerbeek

### Short description

Currently, we stored and return vectors, change this to store and return a shared pointer to const vectors. This allows us to return a single shared pointer on get(), avoiding to copy all vector elements. 

This approach does not work for the answer records, as modified (e.g. TTL) `DNSRecord`s are returned.

Speedup of get() of about 10% in a totally artificial test case of a single insert and many gets(). Should also save a bit on memory. We store `nullptr` for empty vectors and make sure `get()` rerurns a ready-made empty vector in that case.

This not only needs review on the detail level, but also on the general approach!

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X compiled this code
- [X] tested this code
- [ ] included documentation (including possible behaviour changes)
- [X] documented the code
- [ ] added or modified regression test(s)
- [X] added or modified unit test(s)

2024-12-24 09:39 UTC, rgacogne requested changes

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +      assert(*signatures == nullptr || (*signatures)->empty());
This feels wrong. If the condition above is not correct, we could get here with some entries in `*signatures` as long as `entry->d_signatures` doesn't contain any, right?

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +      *signatures = std::make_shared<SigRecsVec>(vec);
Would it make sense to create the shared pointer right away and insert into it? Or at least to move `vec`?

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.hh
> +  // get appended in some cases; the handleHit() code will take measures. In the futrue we might
```suggestion
  // get appended in some cases; the handleHit() code will take measures. In the future we might
```

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.hh
> +  // want a more specialized datastructure than a vector, it would require another level of
```suggestion
  // want a more specialized data structure than a vector, it would require another level of
```

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +  for (const auto& record : *recordSet->d_signatures) {
I think we need to check that `d_signatures` is not `nullptr` first.

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +  for (const auto& authRec : *recordSet->d_authorityRecs) {
Same.

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +      }
I think this can go?

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.cc
> +      }
Same?

2024-12-24 09:39 UTC, rgacogne commented on pdns/recursordist/recursor_cache.hh
> +  // it avoid checking for nullptr, just iterate as for the non-empty case.
I wonder how the optimization holds when we have a lot of threads: we avoid allocating memory which is good (but could be done in a thread-specific pool without any contention) at the cost of having (in some cases, which may be rare?) several threads atomically accessing and updating the same memory location (the shared reference counter). I guess the optimization is worth it if we do not cross NUMA-boundaries, and perhaps a bit less if we do?

2025-01-06 10:46 UTC, omoerbeek commented on pdns/recursordist/recursor_cache.hh
> +  // it avoid checking for nullptr, just iterate as for the non-empty case.
Good point, when I was writing this I was wondering this as well. Many new/delete implementation use some form of locking  as several threads share the same memory pool, so I was guessing it would be beneficial in the typical case. I do not have hard data, though.

2025-01-06 10:49 UTC, rgacogne commented on pdns/recursordist/recursor_cache.hh
> +  // it avoid checking for nullptr, just iterate as for the non-empty case.
I'm OK with ignoring this unless/until it shows up in a performance profile :)

2025-01-06 10:57 UTC, omoerbeek commented on pdns/recursordist/recursor_cache.cc
> +      assert(*signatures == nullptr || (*signatures)->empty());
Right, the assert seems too strict.

2025-01-06 11:10 UTC, rgacogne approved these changes
:+1:

2025-01-06 13:02 UTC, merged