Fixes #8422 abort transaction and return refused to client when update policy returns false
PowerDNS/pdns pull request #8462
Opened 2019-10-24 11:49 UTC by querplis

### Short description
Fixes #8422 abort transaction and return refused to client when update policy returns false
### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2019-10-24 12:14 UTC, rgacogne commented
This would change the documented behavior of the `updatepolicy` callback which, according to the documentation "is called for each record at a time and you can approve or reject any or all".
I'm not sure it makes sense to accept only a part of a DNS update, to be clear, but I think we need to be certain that we actually want to change the semantics of an existing functionality.

2019-10-24 12:16 UTC, cmouse commented
It might be that you don't want to accept IPv6 (or IPv4) updates from hosts. Or you want to avoid accepting anything but A/AAAA updates. I think it might be best to keep track if *any* update succeeded.

2019-10-24 14:26 UTC, querplis commented
@rgacogne it is all or nothing at the moment with this patch , and if i did read rfc correctly it is how it shoud be done

2021-02-08 09:21 UTC, Habbie commented
This patch breaks the documented behaviour. I'd be happy to take a different patch that adds a third return value that causes a transaction abort.

2021-02-08 09:21 UTC, Habbie requested changes
This patch breaks the documented behaviour. I'd be happy to take a different patch that adds a third return value that causes a transaction abort.

2021-02-17 14:28 UTC, Habbie commented
Closing this. As I mentioned above, we'd be happy to take a more flexible patch. Thanks!

2021-02-17 14:28 UTC, closed without merging

2022-02-01 07:59 UTC, jdreichmann commented
As the current behaviour makes it impossible to know from the Answer if an update actually went through when using a lua script for validation, i would be interested in what exactly is meant with the
> "third return value that causes a transaction abort."

Is the lua scripts return value `true`, `false`, `<to_be_added>` meant or something else?

2022-02-01 10:20 UTC, Habbie commented
> Is the lua scripts return value `true`, `false`, `<to_be_added>` meant or something else?

to be added, yes

2022-02-01 11:03 UTC, jdreichmann commented
As that return value changes the result of the entire transaction, it seems a bit counterintuitive to have that as a return value of the evaluation of a single record affecting the whole set - wouldn't a "strict" mode, where a single record failing the policy check cancels the transaction, be a bit more intuitive?

i.e. how important is it to stick to a third possible return value in the lua script which then in turn cancels the entire transaction?

2022-02-01 11:03 UTC, Habbie commented
Note that we are discussing on a closed ticket, and likely these comments will eventually be forgotten. If you want to discuss a new proposal, please open a new ticket.

2022-02-01 11:07 UTC, jdreichmann commented
I'm most interested in gettting the problem described in #8462 fixed and am trying to find out which kind of exact behaviour would be wanted from a patch, as this one sadly got stalled after a review.