Recursor: allow access to some API endpoints with webserver-password even if api-key is empty
PowerDNS/pdns pull request #8890
Opened 2020-03-03 16:14 UTC by swoga

### Short description
Since PR #7489 access to some API endpoints is allowed with the webserver-password (or no auth if the webserver-password is empty) instead of the api-key, but an api-key must still be configured or the requests will be denied.

This PR lifts this requirment and allows access to these endpoints even when the api-key is empty.

### Checklist

I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2020-04-23 13:58 UTC, swoga commented
@rgacogne would you mind reviewing and merging this? :)

2021-02-10 13:02 UTC, omoerbeek commented on pdns/webserver.cc
The logic is now: if the api-key is passed in but does not match, password auth is still tried if allowed. I think that can be confusing.

2021-02-10 13:03 UTC, omoerbeek commented on pdns/webserver.cc
>      g_log<<Logger::Error<<req->logprefix<<"HTTP Request \"" << req->url.path << "\": Authentication by API Key failed" << endl;
A message talking about API Key failure is also given on password failure. Return code is also not relevant.

2021-02-10 13:07 UTC, omoerbeek requested changes
I think this is only acceptable if the code flow of the two types of authentication are more separated and now intertwined as they are now, this PR makes that a bit worse even.

2024-12-06 22:05 UTC, closed without merging