dnsdist, rec: dnstap requires protobuf
PowerDNS/pdns pull request #9477
Opened 2020-09-17 07:59 UTC by pieterlexis

### Short description
Fail the configure when protobuf is disabled or not found but dnstap was
enabled.

Closes #9452

@omoerbeek @rgacogne Would it make sense to define a `HAVE_DNSTAP` that semi-replaces the `HAVE_FSTRM` for all dnstap related code?

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2020-09-17 08:05 UTC, rgacogne requested changes

2020-09-17 08:05 UTC, rgacogne commented on m4/pdns_check_dnstap.m4
> +    AS_IF([test "x$PROTOBUF_LIBS" = "x" -a x"$PROTOC" = "x"], [
```suggestion
    AS_IF([test "x$PROTOBUF_LIBS" = "x" -o x"$PROTOC" = "x"], [
```

2020-09-17 08:06 UTC, pieterlexis commented on m4/pdns_check_dnstap.m4
> +    AS_IF([test "x$PROTOBUF_LIBS" = "x" -a x"$PROTOC" = "x"], [
copy/paste error :)

2020-09-17 08:07 UTC, rgacogne approved these changes

2020-09-17 08:28 UTC, rgacogne commented
> Would it make sense to define a `HAVE_DNSTAP` that semi-replaces the `HAVE_FSTRM` for all dnstap related code?

I think it would make sense to have both. The recursor could then use only `HAVE_DNSTAP`. It's a bit more complicated in dnsdist because we can export dnstap messages over our regular remote logger, which means over plain TCP instead of Frame Streams, so we can technically have some of our dnstap feature enabled as long as protobuf support is available.
I'm pretty sure that's not what most users would expect, though, so I think we should only list `dnstap` as available when both protobuf and fstrm are available.
So how about we define both `HAVE_DNSTAP` and `HAVE_FSTRM`, the recursor can use the first, and I'll review what we are doing in dnsdist?

2020-09-18 10:50 UTC, omoerbeek commented
Let's merge this and then open a separate PR fo the HAVE_DNSTAP/HAVE_FSTRM split.

2020-09-18 10:51 UTC, omoerbeek approved these changes

2020-09-18 10:51 UTC, merged