auth: ignore cryptokeys in presigned zones
PowerDNS/pdns pull request #9496
Opened 2020-09-21 19:07 UTC by mind04

### Short description
Fixes #9492 

### Checklist
I have:
- [x] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [x] compiled this code
- [x] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [x] added or modified regression test(s)
- [ ] added or modified unit test(s)

2020-09-21 21:15 UTC, mnordhoff commented
> Fixes #9492 

That should be fixes #9489, right?

2020-09-21 23:06 UTC, mind04 commented
oops, updated

2020-09-22 04:35 UTC, cmouse commented
Can we add also feature that will warn about this with `pdnsutil show-zone`? Something like `cryptokeys found for presigned zone`?

2020-09-22 04:39 UTC, cmouse requested changes

2020-09-22 04:39 UTC, cmouse commented on pdns/tcpreceiver.cc
> +      DNSName keyname = NSEC3Zone ? DNSName(toBase32Hex(hashQNameWithSalt(ns3pr, zrr.dr.d_name))) : zrr.dr.d_name;
`const DNSName&`

2020-09-22 04:39 UTC, cmouse commented on pdns/tcpreceiver.cc
> +      NSECXEntry& ne = nsecxrepo[keyname];
`const NSECXEntry&`

2020-09-24 12:00 UTC, merged