Move to c++17
PowerDNS/pdns pull request #9913
Opened 2021-01-05 15:56 UTC by omoerbeek

### Short description

Only compile tested with clang on OpenBSD so far.

Creating a PR so the CI and others can easily use this branch to test.

### Checklist

I have:
- [X] read the [CONTRIBUTING.md](https://github.com/PowerDNS/pdns/blob/master/CONTRIBUTING.md) document
- [X] compiled this code
- [ ] tested this code
- [ ] included documentation (including possible behaviour changes)
- [ ] documented the code
- [ ] added or modified regression test(s)
- [ ] added or modified unit test(s)

2021-01-06 06:57 UTC, omoerbeek commented
Old Boost is a hurlde.

2021-01-06 08:43 UTC, rgacogne commented
Do we know which version of Boost fixed C++17 compatibility? Would it make sense to try C++14? I see some errors (in the fuzzers build) related to the removal of `auto_ptr` in C++17, which is still there in C++14.

2021-01-06 08:52 UTC, omoerbeek commented
> Do we know which version of Boost fixed C++17 compatibility? Would it make sense to try C++14? I see some errors (in the fuzzers build) related to the removal of `auto_ptr` in C++17, which is still there in C++14.

I searched for some explicitl statement about C++17 compatibility, but found none.

I am trying CentOS7 now, which has boost 1.53 but seems to have patched `get_pointer.hpp`. Lets see how much other stufff I encounter. For Ubuntu 16, (as used by the fuzzer) which has boost 1.57 another workaround might be needed.  If it all does not work out, I'll try C++14

2021-01-06 08:59 UTC, rgacogne commented
> For Ubuntu 16, (as used by the fuzzer) which has boost 1.57 another workaround might be needed.

OSS-Fuzz intends to move to 20.04 eventually (https://github.com/google/oss-fuzz/issues/3756) but I wouldn't hold my breath.

2021-01-06 10:30 UTC, omoerbeek commented
So Unbuntu 16 as used by the fuzzer is a real problem. I was trying to set up a debug env like the fuzzer uses and found out: while the fuzzer build environment uses clang 12, the newest available clang from ubuntu xenial is 8. And if we use that we hit an issue with the c++ libs not being c++17 level. So getting a debug environment up and running is a hassle. Is there a more direct way to get the same env as the fuzzer uses?

2021-01-06 10:32 UTC, Habbie commented
> Is there a more direct way to get the same env as the fuzzer uses?

https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile ?

2021-01-06 10:32 UTC, rgacogne commented
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally

2021-01-06 11:53 UTC, omoerbeek commented
Ubunitu xenial is a swamp. It's boost 1.57 is using too much deprecated C++11 stuff that has been removed in C++17. Now going for C++14.

2021-01-08 09:15 UTC, omoerbeek commented
Back to c++17 now that the fuzzer issue should be fixed

2021-01-10 16:44 UTC, omoerbeek commented
Both CI and buildbot runs are fine. I needed to add one workaround in the bindbackend code.

2021-01-11 07:51 UTC, Habbie requested changes
Two small things, looks good otherwise!

2021-01-11 07:51 UTC, Habbie commented on builder-support/dockerfiles/Dockerfile.rpmbuild
> +      cd /pdns;
this line does nothing

2021-01-11 07:51 UTC, Habbie commented on m4/ax_cxx_compile_stdcxx_14.m4
> +# =============================================================================
do we need this file?

2021-01-11 09:12 UTC, rgacogne approved these changes

2021-01-11 09:12 UTC, rgacogne commented on modules/bindbackend/bindbackend2.cc
> +      // older (1.53) versions of boost have a exprression for s_state.rbegin()
```suggestion
      // older (1.53) versions of boost have an expression for s_state.rbegin()
```

2021-01-11 10:25 UTC, omoerbeek commented
Processed review comments and squashed it.

2021-01-11 10:27 UTC, Habbie commented on modules/bindbackend/bindbackend2.cc
> +      // older (1.53) versions of boost have an exprression for s_state.rbegin()
```suggestion
      // older (1.53) versions of boost have an expression for s_state.rbegin()
```

2021-01-11 10:39 UTC, merged